import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { KumaRegistry } from "@kuma-ui/next-plugin/registry";
import { css } from "@kuma-ui/core";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={css`
          display: flex;
          align-items: center;
          justify-content: center;
          width: 100%;
          min-height: 100vh;
          margin: 0;
        `}
      >
        <KumaRegistry>{children}</KumaRegistry>
      </body>
    </html>
  );
}
